### ISSUE TITLE
 Sharkle Stuck

### ISSUE THREAD

**Issue by chloeliz** [SamusAranX/Sharkle-for-Mac#1]
Hello, I am having an issue with Sharkle. I moved him off screen and now he is stuck outside of view and I cannot drag him back onto the screen. I have tried to remove the app and reinstall it with no luck. How can I fix this?

**Comment by SamusAranX** [comment]
Try changing your display resolution to something else and back again. This should force all windows back inside your screen bounds.

**Comment by chloeliz** [comment]
That didn't work

**Comment by chloeliz** [comment]
Is there a code I can manipulate to get him to reset his position?

**Comment by SamusAranX** [comment]
Try closing Sharkle, entering `defaults delete com.peterwunder.Sharkle` in the Terminal and then restarting Sharkle. This should reset the last saved window position.

~~I'll release an update that includes a window position reset feature later, though.~~
Here it is: https://github.com/SamusAranX/Sharkle-for-Mac/releases/tag/v1.2

**Comment by chloeliz** [comment]
Wow, thank you so much! I'm so glad to have my little buddy back! Thanks for fixing him and creating him!
